// layout.tsx
import '../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import "flowbite";
import Navbar from "./Navbar";
import Footer from "./Footer";



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Jinki's Projects",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" />
      </head>
      <body>
        <body className={inter.className}>
          <Navbar /> {/* Navbar */}
          {children}
          <Footer/>
          {/* Scripts */}
          <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>
          <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
        </body>
      </body>
    </html>
  )
}
